import { HappeningEvent, SDGMetric, DashboardStats, HeatmapDataPoint } from "./types";

// ── Malaysian Cities & Coordinates ──────────────────────────
export const MALAYSIA_CENTER = { lat: 3.1390, lng: 101.6869 }; // KL

export const CITIES = [
  { name: "Kuala Lumpur", lat: 3.1390, lng: 101.6869 },
  { name: "Petaling Jaya", lat: 3.1073, lng: 101.6067 },
  { name: "George Town", lat: 5.4164, lng: 100.3327 },
  { name: "Johor Bahru", lat: 1.4927, lng: 103.7414 },
  { name: "Ipoh", lat: 4.5975, lng: 101.0901 },
  { name: "Malacca", lat: 2.1896, lng: 102.2501 },
  { name: "Shah Alam", lat: 3.0733, lng: 101.5185 },
  { name: "Kota Kinabalu", lat: 5.9804, lng: 116.0735 },
  { name: "Kuching", lat: 1.5535, lng: 110.3593 },
  { name: "Subang Jaya", lat: 3.0565, lng: 101.5851 },
];

// ── Category Config ─────────────────────────────────────────
export const CATEGORY_CONFIG: Record<string, { label: string; emoji: string; color: string }> = {
  music: { label: "Music", emoji: "🎵", color: "#8B5CF6" },
  arts: { label: "Arts & Culture", emoji: "🎨", color: "#EC4899" },
  food: { label: "Food & Drink", emoji: "🍜", color: "#F59E0B" },
  sports: { label: "Sports", emoji: "⚽", color: "#10B981" },
  tech: { label: "Tech", emoji: "💻", color: "#3B82F6" },
  community: { label: "Community", emoji: "🤝", color: "#6366F1" },
  education: { label: "Education", emoji: "📚", color: "#14B8A6" },
  business: { label: "Business", emoji: "💼", color: "#64748B" },
  wellness: { label: "Wellness", emoji: "🧘", color: "#A3E635" },
  culture: { label: "Culture", emoji: "🏛️", color: "#D946EF" },
  charity: { label: "Charity", emoji: "❤️", color: "#EF4444" },
  nightlife: { label: "Nightlife", emoji: "🌙", color: "#7C3AED" },
  family: { label: "Family", emoji: "👨‍👩‍👧‍👦", color: "#FB923C" },
  outdoor: { label: "Outdoor", emoji: "🌿", color: "#22C55E" },
};

// ── SDG Goals Tracked ───────────────────────────────────────
export const SDG_METRICS: SDGMetric[] = [
  {
    goal: 4,
    title: "Quality Education",
    description: "Educational events, workshops & skill-building sessions across Malaysia",
    eventCount: 342,
    attendeeImpact: 15200,
    trend: 12.5,
    color: "#C5192D",
  },
  {
    goal: 8,
    title: "Decent Work & Economic Growth",
    description: "Job fairs, networking events & entrepreneurship meetups",
    eventCount: 287,
    attendeeImpact: 11800,
    trend: 8.3,
    color: "#A21942",
  },
  {
    goal: 11,
    title: "Sustainable Cities & Communities",
    description: "Community events, cultural festivals & urban sustainability initiatives",
    eventCount: 523,
    attendeeImpact: 28400,
    trend: 15.7,
    color: "#FD9D24",
  },
];

// ── Mock Dashboard Stats ────────────────────────────────────
export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalEvents: 1152,
  totalAttendees: 55400,
  totalOrganizers: 328,
  aiExtractedEvents: 743,
  citiesCovered: 24,
  avgAccuracy: 96.2,
};

// ── Seed Events ─────────────────────────────────────────────
export const SEED_EVENTS: HappeningEvent[] = [
  {
    id: "evt-001",
    title: "KL Jazz Festival 2026",
    description: "Malaysia's premier jazz festival featuring international and local artists. Three stages, food stalls, and art installations at the iconic KLCC Park.",
    date: "2026-03-15",
    time: "17:00",
    endDate: "2026-03-16",
    endTime: "23:00",
    venue: "KLCC Park",
    address: "Kuala Lumpur City Centre",
    city: "Kuala Lumpur",
    state: "W.P. Kuala Lumpur",
    lat: 3.1557,
    lng: 101.7117,
    category: "music",
    tags: ["jazz", "live-music", "outdoor", "festival"],
    imageUrl: "/images/jazz-fest.jpg",
    price: "RM 150",
    isFree: false,
    organizer: "KL Music Foundation",
    attendeeCount: 2400,
    maxCapacity: 5000,
    sdgGoals: [4, 11],
    status: "published",
    source: "manual",
    createdAt: "2026-01-20T08:00:00Z",
    updatedAt: "2026-02-10T12:00:00Z",
  },
  {
    id: "evt-002",
    title: "Penang Street Art Walk",
    description: "Guided walking tour through George Town's UNESCO heritage zone. Explore famous murals, street installations, and hidden art gems with local artists.",
    date: "2026-02-22",
    time: "09:00",
    endTime: "12:00",
    venue: "Armenian Street",
    address: "Lebuh Armenian, George Town",
    city: "George Town",
    state: "Pulau Pinang",
    lat: 5.4164,
    lng: 100.3370,
    category: "arts",
    tags: ["street-art", "walking-tour", "heritage", "culture"],
    imageUrl: "/images/penang-art.jpg",
    price: "Free",
    isFree: true,
    organizer: "Penang Heritage Trust",
    attendeeCount: 45,
    maxCapacity: 60,
    sdgGoals: [4, 11],
    status: "published",
    source: "ai-extracted",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-15T09:00:00Z",
  },
  {
    id: "evt-003",
    title: "Nasi Lemak Cook-Off Championship",
    description: "Who makes the best Nasi Lemak in Malaysia? Join us for this epic cook-off featuring 30 contestants from across the nation. Free tasting for attendees!",
    date: "2026-03-01",
    time: "10:00",
    endTime: "16:00",
    venue: "Dataran Merdeka",
    address: "Jalan Raja, Kuala Lumpur",
    city: "Kuala Lumpur",
    state: "W.P. Kuala Lumpur",
    lat: 3.1480,
    lng: 101.6935,
    category: "food",
    tags: ["cooking", "nasi-lemak", "competition", "food-festival"],
    imageUrl: "/images/nasi-lemak.jpg",
    price: "Free",
    isFree: true,
    organizer: "Malaysian Food Council",
    attendeeCount: 800,
    maxCapacity: 2000,
    sdgGoals: [8, 11],
    status: "published",
    source: "manual",
    createdAt: "2026-01-15T06:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
  {
    id: "evt-004",
    title: "Tech Startup Weekend Cyberjaya",
    description: "54-hour hackathon where developers, designers, and business minds come together to build startups. Prizes worth RM 50,000!",
    date: "2026-03-07",
    time: "18:00",
    endDate: "2026-03-09",
    endTime: "21:00",
    venue: "MDEC Building",
    address: "Persiaran APEC, Cyberjaya",
    city: "Cyberjaya",
    state: "Selangor",
    lat: 2.9213,
    lng: 101.6559,
    category: "tech",
    tags: ["hackathon", "startup", "coding", "innovation"],
    imageUrl: "/images/startup-weekend.jpg",
    price: "RM 80",
    isFree: false,
    organizer: "Startup Grind MY",
    attendeeCount: 150,
    maxCapacity: 200,
    sdgGoals: [4, 8],
    status: "published",
    source: "ai-extracted",
    createdAt: "2026-02-05T07:00:00Z",
    updatedAt: "2026-02-14T11:00:00Z",
  },
  {
    id: "evt-005",
    title: "Thaipusam Festival Batu Caves",
    description: "Experience the vibrant Thaipusam celebration at Batu Caves. Witness the spectacular kavadi procession and immerse in Malaysian Indian culture.",
    date: "2026-02-20",
    time: "05:00",
    endTime: "22:00",
    venue: "Batu Caves Temple",
    address: "Gombak, Selangor",
    city: "Kuala Lumpur",
    state: "Selangor",
    lat: 3.2379,
    lng: 101.6840,
    category: "culture",
    tags: ["thaipusam", "festival", "culture", "heritage", "temple"],
    imageUrl: "/images/thaipusam.jpg",
    price: "Free",
    isFree: true,
    organizer: "Batu Caves Temple Committee",
    attendeeCount: 50000,
    sdgGoals: [11],
    status: "published",
    source: "manual",
    createdAt: "2026-01-10T04:00:00Z",
    updatedAt: "2026-02-18T08:00:00Z",
  },
  {
    id: "evt-006",
    title: "JB Marathon 2026",
    description: "Annual Johor Bahru marathon with 5K, 10K, half and full marathon categories. Route passes through iconic JB landmarks.",
    date: "2026-04-05",
    time: "05:30",
    endTime: "12:00",
    venue: "Dataran Bandaraya JB",
    address: "Jalan Tun Abdul Razak, Johor Bahru",
    city: "Johor Bahru",
    state: "Johor",
    lat: 1.4616,
    lng: 103.7636,
    category: "sports",
    tags: ["marathon", "running", "fitness", "outdoor"],
    imageUrl: "/images/jb-marathon.jpg",
    price: "RM 60",
    isFree: false,
    organizer: "JB Running Club",
    attendeeCount: 3200,
    maxCapacity: 8000,
    sdgGoals: [11],
    status: "published",
    source: "manual",
    createdAt: "2026-01-25T09:00:00Z",
    updatedAt: "2026-02-16T10:00:00Z",
  },
  {
    id: "evt-007",
    title: "Charity Iftar at Masjid Negara",
    description: "Community iftar gathering open to all. Featuring traditional Malaysian dishes and cultural performances. Donations go to Tabung Asnaf.",
    date: "2026-03-10",
    time: "19:00",
    endTime: "21:30",
    venue: "Masjid Negara",
    address: "Jalan Perdana, Kuala Lumpur",
    city: "Kuala Lumpur",
    state: "W.P. Kuala Lumpur",
    lat: 3.1415,
    lng: 101.6918,
    category: "charity",
    tags: ["ramadan", "iftar", "charity", "community", "culture"],
    imageUrl: "/images/iftar.jpg",
    price: "Free",
    isFree: true,
    organizer: "Yayasan Kebajikan MY",
    attendeeCount: 500,
    maxCapacity: 1000,
    sdgGoals: [4, 11],
    status: "published",
    source: "ai-extracted",
    createdAt: "2026-02-08T06:00:00Z",
    updatedAt: "2026-02-17T07:00:00Z",
  },
  {
    id: "evt-008",
    title: "Ipoh White Coffee Festival",
    description: "Celebrate Ipoh's world-famous white coffee! Barista competitions, coffee art, bean-to-cup workshops, and unlimited tasting sessions.",
    date: "2026-03-22",
    time: "08:00",
    endDate: "2026-03-23",
    endTime: "18:00",
    venue: "Ipoh Railway Station",
    address: "Jalan Panglima Bukit Gantang Wahab, Ipoh",
    city: "Ipoh",
    state: "Perak",
    lat: 4.5950,
    lng: 101.0870,
    category: "food",
    tags: ["coffee", "festival", "barista", "workshop"],
    imageUrl: "/images/ipoh-coffee.jpg",
    price: "RM 25",
    isFree: false,
    organizer: "Ipoh Coffee Society",
    attendeeCount: 1200,
    maxCapacity: 3000,
    sdgGoals: [8, 11],
    status: "published",
    source: "manual",
    createdAt: "2026-02-01T05:00:00Z",
    updatedAt: "2026-02-15T12:00:00Z",
  },
  {
    id: "evt-009",
    title: "Sunrise Yoga at Tanjung Aru",
    description: "Start your weekend with a rejuvenating sunrise yoga session on the beach. All levels welcome. Mats provided. Ends with a healthy breakfast.",
    date: "2026-02-28",
    time: "06:00",
    endTime: "08:30",
    venue: "Tanjung Aru Beach",
    address: "Tanjung Aru, Kota Kinabalu",
    city: "Kota Kinabalu",
    state: "Sabah",
    lat: 5.9551,
    lng: 116.0459,
    category: "wellness",
    tags: ["yoga", "beach", "sunrise", "wellness", "outdoor"],
    imageUrl: "/images/yoga-kk.jpg",
    price: "RM 30",
    isFree: false,
    organizer: "KK Wellness Collective",
    attendeeCount: 35,
    maxCapacity: 50,
    sdgGoals: [11],
    status: "published",
    source: "ai-extracted",
    createdAt: "2026-02-10T03:00:00Z",
    updatedAt: "2026-02-17T06:00:00Z",
  },
  {
    id: "evt-010",
    title: "Kuching Cat Festival",
    description: "The quirkiest festival in Sarawak! Cat costume parade, cat café pop-ups, feline art exhibition, and adoption drives. Fun for the whole family!",
    date: "2026-04-12",
    time: "10:00",
    endDate: "2026-04-13",
    endTime: "20:00",
    venue: "Waterfront Promenade",
    address: "Main Bazaar, Kuching",
    city: "Kuching",
    state: "Sarawak",
    lat: 1.5580,
    lng: 110.3492,
    category: "family",
    tags: ["cats", "festival", "family", "fun", "adoption"],
    imageUrl: "/images/cat-fest.jpg",
    price: "Free",
    isFree: true,
    organizer: "Kuching City Council",
    attendeeCount: 4500,
    maxCapacity: 10000,
    sdgGoals: [11],
    status: "published",
    source: "manual",
    createdAt: "2026-02-03T08:00:00Z",
    updatedAt: "2026-02-16T09:00:00Z",
  },
];

// ── Mock Heatmap Data ───────────────────────────────────────
export const MOCK_HEATMAP_DATA: HeatmapDataPoint[] = [
  { lat: 3.1390, lng: 101.6869, weight: 95 },
  { lat: 3.1557, lng: 101.7117, weight: 80 },
  { lat: 3.1480, lng: 101.6935, weight: 70 },
  { lat: 3.1073, lng: 101.6067, weight: 55 },
  { lat: 5.4164, lng: 100.3327, weight: 60 },
  { lat: 1.4927, lng: 103.7414, weight: 50 },
  { lat: 4.5975, lng: 101.0901, weight: 35 },
  { lat: 2.1896, lng: 102.2501, weight: 40 },
  { lat: 5.9804, lng: 116.0735, weight: 30 },
  { lat: 1.5535, lng: 110.3593, weight: 28 },
  { lat: 3.0565, lng: 101.5851, weight: 45 },
  { lat: 3.0733, lng: 101.5185, weight: 38 },
  { lat: 2.9213, lng: 101.6559, weight: 25 },
  { lat: 3.2379, lng: 101.6840, weight: 65 },
];
